server:
    port: 8072
    servlet:
        context-path: /myservice
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://123.56.161.89:3306/myservice?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        username: ruanhua
        password: ruanhua2008

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
        # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
        map-underscore-to-camel-case: true

springdoc:
    packagesToScan: com.cn.myservice.controller